name: Update PRs

on:
  push:
    branches:
      - main

jobs:
  update-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Merge upstream branch into PRs
        uses: wiggins-twentyideas/pr-updater-action@4fca5082a748c6a0d87f2920228c81c69c2445b6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude_drafts: "true"
