name: Update PRs

on:
  push:
    branches:
      - main

jobs:
  update-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Merge upstream branch into PRs
        uses: wiggins-twentyideas/pr-updater-action@7b3f59e6a5d6e997b26d2d951a57c89b062e8ccd
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude_drafts: "true"
