name: Update PRs

on:
  push:
    branches:
      - main

jobs:
  update-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Merge upstream branch into PRs
        uses: wiggins-twentyideas/pr-updater-action@ef90522b47cf57fe9a4d09730ff47151599c5c8d
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude_drafts: "true"
