name: Update PRs

on:
  push:
    branches:
      - main

jobs:
  update-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Merge upstream branch into PRs
        uses: wiggins-twentyideas/pr-updater-action@ad954ab5d1d816ff3cf77e2b4f96a55dd5438f01
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude_drafts: "true"
